-- SQLite
CREATE TABLE OTP (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	OTPCode NUMERIC NOT NULL,
	Email TEXT NOT NULL,
    --CREATEDDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   -- CREATEDDATE REAL DEFAULT (datetime('now', 'localtime')),
    CREATEDDATE datetime ,
    OTPCheckCount INTEGER NOT NULL
);